// Generated by scripts/generate-contract.mjs. Edit interface-contract.json.
#pragma once
namespace Pins {
constexpr int SafetyLoop = 1;
constexpr int HomeSwitch = 2;
constexpr int AuxControl = 3;
constexpr int RfD0 = 4;
constexpr int RfD1 = 5;
constexpr int RfD2 = 6;
constexpr int RfD3 = 7;
constexpr int RfD4 = 8;
constexpr int MramCs = 9;
constexpr int CounterCs = 10;
constexpr int SpiMosi = 11;
constexpr int SpiClock = 12;
constexpr int SpiMiso = 13;
constexpr int RfLearn = 14;
constexpr int RfTxId = 15;
constexpr int RfModeInd = 16;
constexpr int VfdTx = 17;
constexpr int VfdRx = 18;
constexpr int UsbDm = 19;
constexpr int UsbDp = 20;
constexpr int StatusLed = 21;
constexpr int HoldToRun = 38;
constexpr int ServiceUp = 39;
constexpr int ServiceDown = 40;
constexpr int LightControl = 41;
constexpr int CoupledVfdEnable = 42;
constexpr int I2cSda = 47;
constexpr int I2cScl = 48;
constexpr unsigned ContractVersion = 1;
constexpr bool DeploymentReady = false;
}
