import fs from 'node:fs';
import assert from 'node:assert/strict';
const root=new URL('../../',import.meta.url);
const c=JSON.parse(fs.readFileSync(new URL('firmware/interface-contract.json',root),'utf8'));
const evidence=JSON.parse(fs.readFileSync(new URL(c.evidence,root),'utf8'));
assert.equal(evidence.result,'PASS');
assert.equal(evidence.checkCount,227);
const aliases={SafetyLoop:'SAFETY_MON',HomeSwitch:'HOME',ServiceKey:'SERVICE_KEY',UpperLimit:'LIMIT_UP',LowerLimit:'LIMIT_DOWN',MramCs:'MRAM_CS_N',CounterCs:'COUNTER_CS_N',SpiMosi:'SPI_MOSI',SpiClock:'SPI_SCK',SpiMiso:'SPI_MISO',RfLearn:'RF_LEARN',RfTxId:'RF_TX_ID',RfModeInd:'RF_MODE_IND',VfdTx:'VFD_TX_3V3',VfdRx:'VFD_RX_3V3',UsbDm:'/MCU_Storage/USB_D-',UsbDp:'/MCU_Storage/USB_D+',StatusLed:'/MCU_Storage/STATUS_LED',HoldToRun:'HOLD_TO_RUN',ServiceUp:'SERVICE_UP',ServiceDown:'SERVICE_DOWN',LightControl:'LIGHT_CTRL',VfdCommsEnable:'VFD_COMMS_ENABLE',I2cSda:'I2C_SDA',I2cScl:'I2C_SCL'};
for(let n=0;n<5;n++)aliases['RfD'+n]='RF_D'+n;
for(const [name,pin] of Object.entries(c.pins)){
 const fn = pin === 43 ? 'TXD0_37' : pin === 44 ? 'RXD0_36' : null;
 assert.ok(evidence.u10.some(n=>n.net===aliases[name]&&(fn ? n.function===fn : n.function.startsWith(`IO${pin}_`))),name);
}
assert.equal(c.version,2);
assert.deepEqual([c.pins.UpperLimit,c.pins.LowerLimit,c.pins.ServiceKey,c.pins.VfdCommsEnable],[43,44,3,42]);
assert.equal(c.pins.AuxControl,undefined);
assert.ok(!Object.values(c.pins).some(p=>p>=26&&p<=37));
assert.deepEqual(c.peripherals.vfd.allowedOperations,['STOP','MONITOR','READ']);
assert.equal(c.deploymentReady,false);
const main=fs.readFileSync(new URL('firmware/src/main.cpp',root),'utf8');
assert.doesNotMatch(main,/attachInterrupt|AuxControl|CoupledVfdEnable|PositionUpPulse|PositionDownPulse|ESP\.restart/);
assert.doesNotMatch(main,/digitalWrite\(Pins::ServiceKey|pinMode\(Pins::ServiceKey,\s*OUTPUT|Serial0\.begin/);
assert.ok(main.indexOf('Serial0.end()') < main.indexOf('Pins::UpperLimit, Pins::LowerLimit, Pins::ServiceKey'));
assert.match(main,/HardwareSerial VfdSerial\(1\)/);
assert.match(main,/i.hardwareReady = Pins::DeploymentReady/);
const loop=main.slice(main.indexOf('void loop()'));
assert.ok(loop.indexOf('manualStop.update(')<loop.indexOf('serviceVfd(now)'));
assert.ok(loop.indexOf('diagnosticVfd.stop(now)')<loop.indexOf('serviceVfd(now)'));
assert.match(main,/manual_control_priority/);
assert.match(main,/FieldContinuityQualified = false/);
assert.match(main,/esp_log_set_vprintf\(discardUartLog\)/);
assert.match(main,/esp_rom_install_channel_putc\(1, nullptr\)/);
assert.match(main,/esp_rom_install_channel_putc\(2, nullptr\)/);
assert.match(main,/VfdSerial.begin\(9600, SERIAL_8N1, Pins::VfdRx, Pins::VfdTx\)/);
const ini=fs.readFileSync(new URL('firmware/platformio.ini',root),'utf8');
assert.match(ini,/-DCORE_DEBUG_LEVEL=0/);
assert.match(ini,/-DARDUINO_USB_CDC_ON_BOOT=1/);
const board=JSON.parse(fs.readFileSync(new URL('firmware/boards/elevator-n16r8.json',root),'utf8'));
assert.equal(board.upload.flash_size,'16MB');assert.equal(board.build.arduino.memory_type,'qio_opi');
console.log('PASS contract v2: finalized wiring, UART0 disabled, diagnostic UART only, motion inhibited');
